adim: 768
aheads: 12
eunits: 3072
elayers: 12
transformer_input_layer: conv3d
dropout_rate: 0.1
transformer_attn_dropout_rate: 0.1
transformer_encoder_attn_layer_type: rel_mha
macaron_style: True
use_cnn_module: True
cnn_module_kernel: 31
zero_triu: False
a_upsample_ratio: 1
relu_type: swish
ddim: 768
dheads: 12
dunits: 3072
dlayers: 6
lsm_weight: 0.1
transformer_length_normalized_loss: False
mtlalpha: 0.1
ctc_type: builtin
rel_pos_type: latest

aux_adim: 768
aux_aheads: 12
aux_eunits: 3072
aux_elayers: 12
aux_transformer_input_layer: conv1d
aux_dropout_rate: 0.1
aux_transformer_attn_dropout_rate: 0.1
aux_transformer_encoder_attn_layer_type: rel_mha
aux_macaron_style: True
aux_use_cnn_module: True
aux_cnn_module_kernel: 31
aux_zero_triu: False
aux_a_upsample_ratio: 1
aux_relu_type: swish
aux_dunits: 3072
aux_dlayers: 6
aux_lsm_weight: 0.1
aux_transformer_length_normalized_loss: False
aux_mtlalpha: 0.1
aux_ctc_type: builtin
aux_rel_pos_type: latest

fusion_hdim: 8192
fusion_norm: batchnorm
